'use strict';
(async()=>{
const OWNER='Hiijee220', REPO='undangan-ulang-tahun-anak', DRAFT='birthday-invitation-draft-v2', CONNECTION='birthday-github-connection-v1';
let published;try{const r=await fetch('config.json',{cache:'no-store'});if(!r.ok)throw Error('Data gagal dimuat');published=await r.json()}catch(e){document.getElementById('status').textContent=e.message;return}
let data=structuredClone(published),base=JSON.stringify(published);try{const draft=JSON.parse(localStorage.getItem(DRAFT));if(draft?.base===base&&draft?.data)data=draft.data}catch{/* Use the published version. */}
const specs={hero:{eyebrow:['Label pembuka'],name:['Nama anak'],age:['Usia (tahun)','number'],subtitle:['Kalimat singkat'],portrait:['Foto utama','image'],cover:['Foto sampul tambahan (opsional)','image']},invitation:{greeting:['Sapaan'],message:['Isi undangan','textarea'],closing:['Kalimat penutup'],from:['Dari keluarga']},event:{date:['Tanggal','date'],start:['Mulai (WITA)','time'],end:['Selesai (WITA)','time'],venue:['Nama tempat'],address:['Alamat lengkap','textarea'],map:['Tautan Google Maps','url'],dress:['Kode pakaian']},extras:{galleryTitle:['Judul galeri'],music:['Tautan langsung MP3/OGG (https)','url'],whatsapp:['Nomor WhatsApp konfirmasi (628...)','tel'],rsvpMessage:['Teks konfirmasi; {name} = nama anak'],gift:['Informasi hadiah (opsional)','textarea'],note:['Pesan tentang hadiah','textarea']},copy:{coverTitle:['Judul sampul'],coverAccent:['Judul sampul berwarna'],coverIntro:['Label sampul'],coverHint:['Petunjuk buka'],heroLine:['Judul utama baris pertama'],heroAccent:['Judul utama berwarna'],heroPrefix:['Kata sebelum nama'],ticker:['Teks pita berjalan'],countdownTitle:['Judul hitung mundur'],countdownNote:['Pesan hitung mundur'],eventTitle:['Judul acara'],eventAccent:['Judul acara berwarna'],eventIntro:['Pengantar detail acara','textarea'],galleryIntro:['Pengantar galeri'],rsvpTitle:['Judul konfirmasi'],rsvpAccent:['Judul konfirmasi berwarna'],rsvpIntro:['Pesan konfirmasi','textarea'],footerTitle:['Penutup baris pertama'],footerAccent:['Penutup baris kedua']},theme:{red:['Merah','color'],blue:['Biru','color'],gold:['Kuning','color'],cream:['Latar terang','color']}};
const sectionLabels={countdown:'Hitung mundur',story:'Pesan undangan',gallery:'Galeri',details:'Detail acara',rsvp:'Konfirmasi',gift:'Hadiah'};
const status=(message,error=false)=>{const el=document.getElementById('status');el.textContent=message;el.className='status '+(error?'error':'ok')};
const field=(group,key,label,type='text',object=data)=>{const wrap=document.createElement('label');wrap.className='field'+(['message','address','note','gift'].includes(key)?' full':'');wrap.textContent=label;let input;if(type==='textarea'){input=document.createElement('textarea')}else{input=document.createElement('input');input.type=type==='image'?'file':type;if(type==='image')input.accept='image/jpeg,image/png,image/webp'}if(type!=='image')input.value=object[group][key]??'';input.dataset.path=`${group}.${key}`;wrap.append(input);if(type==='image'){const note=document.createElement('small');note.textContent=object[group][key]?'Foto sudah terpasang. Unggah baru untuk mengganti.':'Belum ada foto';wrap.append(note);input.addEventListener('change',async()=>{try{object[group][key]=await resizeImage(input.files[0]);note.textContent='Foto baru siap disimpan';saveDraft();refresh()}catch(e){status(e.message,true)}})}else input.addEventListener('input',()=>{object[group][key]=input.value;saveDraft()});return wrap};
for(const[group,items]of Object.entries(specs)){const target=document.querySelector(`[data-fields="${group}"]`);for(const[key,[label,type]]of Object.entries(items))target.append(field(group,key,label,type))}
for(const[key,label]of Object.entries(sectionLabels)){const wrap=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=data.sections[key]!==false;input.addEventListener('change',()=>{data.sections[key]=input.checked;saveDraft()});wrap.append(input,label);document.getElementById('sectionsEditor').append(wrap)}
function saveDraft(){try{localStorage.setItem(DRAFT,JSON.stringify({base,data}));status('Konsep tersimpan. Klik Simpan & perbarui undangan untuk menerbitkan.')}catch{status('Penyimpanan browser penuh. Kurangi ukuran foto lalu coba lagi.',true)}}
function resizeImage(file){return new Promise((resolve,reject)=>{if(!file)return reject(Error('Pilih foto.'));if(file.size>12*1024*1024)return reject(Error('Foto sumber terlalu besar (maksimal 12 MB).'));if(!['image/jpeg','image/png','image/webp'].includes(file.type))return reject(Error('Gunakan JPG, PNG, atau WebP.'));const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);const canvas=document.createElement('canvas'),scale=Math.min(1,1000/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);let quality=.82,out=canvas.toDataURL('image/jpeg',quality);while(out.length>1100000&&quality>.45){quality-=.1;out=canvas.toDataURL('image/jpeg',quality)}out.length>1400000?reject(Error('Foto terlalu besar setelah diperkecil.')):resolve(out)};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Foto gagal dibaca.'))};img.src=url})}
function gallery(){const target=document.getElementById('galleryEditor');target.replaceChildren();data.extras.gallery.forEach((item,i)=>{const row=document.createElement('div');row.className='gallery-row';const title=document.createElement('strong');title.textContent=`Foto ${i+1}`;const cap=document.createElement('input');cap.placeholder='Keterangan foto';cap.value=item.caption||'';cap.addEventListener('input',()=>{item.caption=cap.value;saveDraft()});const file=document.createElement('input');file.type='file';file.accept='image/jpeg,image/png,image/webp';file.addEventListener('change',async()=>{try{item.src=await resizeImage(file.files[0]);saveDraft();status(`Foto ${i+1} siap diterbitkan.`)}catch(e){status(e.message,true)}});const remove=document.createElement('button');remove.type='button';remove.className='secondary';remove.textContent='Hapus foto';remove.addEventListener('click',()=>{data.extras.gallery.splice(i,1);gallery();saveDraft()});row.append(title,document.createElement('br'),cap,file,remove);target.append(row)})}gallery();document.getElementById('addPhoto').onclick=()=>{data.extras.gallery.push({src:'',caption:''});gallery();saveDraft()};
document.getElementById('download').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}));a.download='config.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
function refresh(){const iframe=document.getElementById('preview');const url=new URL('index.html',location.href);fetch(url).then(r=>r.text()).then(html=>{const json=JSON.stringify(data).replace(/</g,'\\u003c');iframe.srcdoc=html.replace('<script src="app.js?v=4" defer></script>',`<script>const nativeFetch=window.fetch;window.fetch=(url,options)=>String(url).startsWith('config.json')?Promise.resolve(new Response(${JSON.stringify(json)},{headers:{'Content-Type':'application/json'}})):nativeFetch(url,options);<\/script><script src="app.js?v=4" defer></script>`).replace('<link rel="stylesheet" href="style.css?v=5">',`<base href="${new URL('.',location.href).href}"><link rel="stylesheet" href="style.css?v=5">`)}).catch(()=>status('Pratinjau gagal dimuat.',true))}
document.getElementById('refreshPreview').onclick=()=>{saveDraft();refresh()};
function base64Unicode(str){const bytes=new TextEncoder().encode(str);let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary)}
async function api(path,token,options={}){const res=await fetch('https://api.github.com'+path,{...options,headers:{'Accept':'application/vnd.github+json','Authorization':'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(options.headers||{})}});const json=await res.json().catch(()=>({}));if(!res.ok)throw Error(json.message||`GitHub API: ${res.status}`);return json}
const connection=document.getElementById('connection'),connected=document.getElementById('connected');
function showConnection(){const hasToken=Boolean(sessionStorage.getItem(CONNECTION));connection.hidden=hasToken;connected.hidden=!hasToken}
showConnection();
document.getElementById('connect').onclick=async()=>{const token=document.getElementById('token').value.trim();if(!token)return status('Tempel token GitHub terlebih dahulu.',true);const button=document.getElementById('connect');button.disabled=true;status('Memeriksa akun dan akses repositori...');try{const user=await api('/user',token);if(user.login?.toLowerCase()!==OWNER.toLowerCase())throw Error(`Token ini milik akun ${user.login}, bukan ${OWNER}.`);await api(`/repos/${OWNER}/${REPO}/contents/config.json?ref=main`,token);sessionStorage.setItem(CONNECTION,token);document.getElementById('token').value='';showConnection();status('GitHub terhubung untuk sesi ini. Sekarang klik Simpan & perbarui undangan setiap kali selesai mengedit.')}catch(e){status('Gagal menghubungkan: '+e.message,true)}finally{button.disabled=false}};
document.getElementById('disconnect').onclick=()=>{sessionStorage.removeItem(CONNECTION);showConnection();status('Sambungan GitHub sesi ini telah diputus. Konsep tetap tersimpan.')};
document.getElementById('publish').onclick=async()=>{const token=sessionStorage.getItem(CONNECTION);if(!token){status('Hubungkan akun GitHub untuk sesi ini sebelum menyimpan.',true);connection.scrollIntoView({behavior:'smooth'});return}const button=document.getElementById('publish');button.disabled=true;status('Menyimpan ke GitHub...');try{const path=`/repos/${OWNER}/${REPO}/contents/config.json`;const old=await api(path+'?ref=main',token);if(old.type!=='file')throw Error('config.json tidak ditemukan di branch main.');const remote=JSON.parse(decodeURIComponent(escape(atob(old.content.replace(/\s/g,'')))));if(JSON.stringify(remote)!==base)throw Error('Undangan sudah diperbarui dari perangkat lain. Unduh cadangan konsep, lalu muat ulang admin sebelum mengedit lagi.');const content=JSON.stringify(data,null,2)+'\n';if(new TextEncoder().encode(content).length>950000)throw Error('Total foto terlalu besar. Kurangi jumlah atau ukuran foto sebelum menyimpan.');const result=await api(path,token,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Perbarui undangan melalui admin',content:base64Unicode(content),sha:old.sha,branch:'main'})});published=structuredClone(data);base=JSON.stringify(published);localStorage.removeItem(DRAFT);status(`Tersimpan! Undangan publik akan diperbarui otomatis setelah GitHub Pages membangun. Commit ${result.commit?.sha?.slice(0,7)||''}.`)}catch(e){if(/401|Bad credentials|expired/i.test(e.message)){sessionStorage.removeItem(CONNECTION);showConnection()}status('Gagal menyimpan: '+e.message,true)}finally{button.disabled=false}};
})();
