'use strict';
(async()=>{
const safeURL=(url,protocols=['https:'])=>{if(typeof url!=='string'||!url.trim())return '';try{const u=new URL(url,document.baseURI);return protocols.includes(u.protocol)?u.href:''}catch{return''}};
const themeAssets=new Set(['spider-swing.jpeg','spider-relax.jpeg','spider-hang.jpeg','spider-hero.jpeg']);
const isThemeAsset=src=>typeof src==='string'&&themeAssets.has(src.split(/[/?#]/).pop());
let data;try{const response=await fetch('config.json',{cache:'no-store'});if(!response.ok)throw Error('config');data=await response.json();try{const cloud=window.__INVITATION_PREVIEW__?null:await import('./firebase-store.js');const latest=cloud?await cloud.loadInvitation():null;if(latest?.hero&&latest?.event)data=latest}catch(e){console.warn('Menggunakan undangan cadangan:',e)}}catch{document.body.textContent='Undangan belum dapat dimuat. Coba segarkan halaman.';return}
const get=path=>path.split('.').reduce((o,k)=>o?.[k],data)??'';
const setText=(el,value)=>{el.textContent=String(value)};
document.querySelectorAll('[data-bind]').forEach(el=>setText(el,get(el.dataset.bind)));
for(const [key,visible] of Object.entries(data.sections||{})){const el=document.getElementById(key);if(el)el.hidden=!visible; if(key==='details')document.getElementById('event').hidden=!visible}
document.title=`Undangan Ulang Tahun ${data.hero.name}`;
const coverPhoto=isThemeAsset(data.hero.cover)?'':safeURL(data.hero.cover,['https:','data:']);if(coverPhoto){document.getElementById('customCoverImage').src=coverPhoto;document.getElementById('customCover').hidden=false}
for(const color of ['red','blue','gold','cream'])if(/^#[0-9a-fA-F]{6}$/.test(data.theme?.[color]||''))document.documentElement.style.setProperty('--'+color,data.theme[color]);
const params=new URLSearchParams(location.search),invitee=(params.get('to')||'Sahabat dan keluarga').slice(0,100);setText(document.getElementById('invitee'),invitee);
const portrait=isThemeAsset(data.hero.portrait)?'':safeURL(data.hero.portrait,['https:','data:']);if(portrait){const img=document.getElementById('heroPortrait');img.src=portrait;img.hidden=false;document.querySelector('.portrait-default').hidden=true}
const grid=document.getElementById('galleryGrid');const photos=(data.extras.gallery||[]).filter(item=>!isThemeAsset(item.src)&&safeURL(item.src,['https:','data:']));if(photos.length){photos.forEach(item=>{const wrap=document.createElement('div');wrap.className='gallery-item gallery-item-'+(grid.children.length+1);const img=document.createElement('img');img.src=safeURL(item.src,['https:','data:']);img.alt=item.caption||'Foto anak';img.loading='lazy';const caption=document.createElement('p');setText(caption,item.caption||'Momen spesial');wrap.append(img,caption);grid.append(wrap)})}else{const empty=document.createElement('div');empty.className='gallery-empty';empty.textContent='Foto-foto spesial anak akan tampil di sini setelah diunggah lewat admin ✦';grid.append(empty)}
const start=new Date(`${data.event.date}T${data.event.start||'00:00'}:00+08:00`),end=new Date(`${data.event.date}T${data.event.end||'23:59'}:00+08:00`);const valid=Boolean(data.event.date)&&!Number.isNaN(start.getTime());document.getElementById('eventDate').textContent=valid?new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Makassar'}).format(start):'Tanggal menyusul';document.getElementById('eventTime').textContent= data.event.start?`${data.event.start} – ${data.event.end||'selesai'} WITA`:'Waktu menyusul';
const calendar=document.getElementById('calendarLink');if(valid){const utc=date=>date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');calendar.href=`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent('Ulang Tahun '+data.hero.name)}&dates=${utc(start)}/${utc(end>start?end:new Date(start.getTime()+7200000))}&details=${encodeURIComponent(data.invitation.message)}&location=${encodeURIComponent(data.event.venue+', '+data.event.address)}`}else calendar.hidden=true;
const map=document.getElementById('mapLink');map.href=safeURL(data.event.map)||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(data.event.venue+' '+data.event.address)}`;
const phone=String(data.extras.whatsapp||'').replace(/\D/g,'');const rsvp=document.getElementById('rsvpLink');if(phone){rsvp.href=`https://wa.me/${phone}?text=${encodeURIComponent((data.extras.rsvpMessage||'Halo, saya akan hadir di ulang tahun {name}.').replaceAll('{name}',data.hero.name)+' Dari: '+invitee)}`}else{rsvp.hidden=true;document.getElementById('rsvpHint').textContent='Kontak konfirmasi akan segera tersedia.'}
function tick(){const diff=valid?Math.max(0,start.getTime()-Date.now()):0;const vals=[Math.floor(diff/86400000),Math.floor(diff/3600000)%24,Math.floor(diff/60000)%60,Math.floor(diff/1000)%60];['days','hours','minutes','seconds'].forEach((id,i)=>document.getElementById(id).textContent=String(vals[i]).padStart(2,'0'));if(valid&&diff===0)document.getElementById('countdownNote').textContent='Hari istimewa telah tiba!'}tick();setInterval(tick,1000);
const audio=document.getElementById('music'),btn=document.getElementById('musicButton'),music=safeURL(data.extras.music,['https:']);if(music)audio.src=music;
let musicContext,musicTimer,musicStep=0,musicPlaying=false;
const melody=[523.25,659.25,783.99,659.25,698.46,783.99,880,783.99,659.25,587.33,659.25,523.25,587.33,659.25,523.25,392];
function playNote(frequency){if(!musicContext)return;const now=musicContext.currentTime,voice=musicContext.createOscillator(),gain=musicContext.createGain();voice.type='sine';voice.frequency.setValueAtTime(frequency,now);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.075,now+.025);gain.gain.exponentialRampToValueAtTime(.0001,now+.29);voice.connect(gain).connect(musicContext.destination);voice.start(now);voice.stop(now+.31)}
async function startMusic(){try{if(music){await audio.play()}else{const AudioContextType=window.AudioContext||window.webkitAudioContext;if(!AudioContextType)throw Error('Audio tidak tersedia');musicContext??=new AudioContextType();await musicContext.resume();if(!musicTimer){playNote(melody[musicStep++%melody.length]);musicTimer=setInterval(()=>playNote(melody[musicStep++%melody.length]),325)}}musicPlaying=true;btn.classList.add('playing');btn.setAttribute('aria-label','Jeda musik')}catch{btn.title='Musik diblokir browser. Ketuk lagi untuk mencoba.'}}
function stopMusic(){audio.pause();if(musicTimer){clearInterval(musicTimer);musicTimer=0}musicContext?.suspend();musicPlaying=false;btn.classList.remove('playing');btn.setAttribute('aria-label','Putar musik')}
btn.addEventListener('click',()=>musicPlaying?stopMusic():startMusic());
const cover=document.getElementById('cover'),main=document.getElementById('main');
const flyer=document.getElementById('scrollSpider'),realFlyer=document.getElementById('realSpider'),flightWeb=document.getElementById('flightWeb'),webShadow=document.getElementById('flightWebShadow'),webThread=document.getElementById('flightWebThread'),realShadow=document.getElementById('realWebShadow'),realThread=document.getElementById('realWebThread'),spiders=document.querySelector('.dangling-spiders');let flightFrame=0,flightWidth=innerWidth,flightHeight=Math.max(innerHeight,document.documentElement.clientHeight);
// Remove the pale sky in the supplied photo at render time, keeping the original file untouched.
const realSvg=realFlyer.querySelector('svg'),svgNS='http://www.w3.org/2000/svg',skyFilter=document.createElementNS(svgNS,'filter'),keyMatrix=document.createElementNS(svgNS,'feColorMatrix');skyFilter.id='skyKey';skyFilter.setAttribute('x','0%');skyFilter.setAttribute('y','0%');skyFilter.setAttribute('width','100%');skyFilter.setAttribute('height','100%');keyMatrix.setAttribute('type','matrix');keyMatrix.setAttribute('values','1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  -.56 -.56 -.56 0 1.50');keyMatrix.setAttribute('result','skyMasked');const alphaComposite=document.createElementNS(svgNS,'feComposite');alphaComposite.setAttribute('in','skyMasked');alphaComposite.setAttribute('in2','SourceAlpha');alphaComposite.setAttribute('operator','in');skyFilter.append(keyMatrix,alphaComposite);realSvg.querySelector('defs').append(skyFilter);realSvg.querySelector('image').setAttribute('filter','url(#skyKey)');
const spiderArt='<svg viewBox="0 0 80 74" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="4.4" stroke-linecap="round" stroke-linejoin="round"><path d="M31 37 16 25 3 29 M30 42 15 41 5 55 M31 48 17 58 13 72 M49 37 64 25 77 29 M50 42 65 41 75 55 M49 48 63 58 67 72 M32 34 22 15 12 12 M48 34 58 15 68 12"/></g><ellipse cx="40" cy="47" rx="15" ry="18" fill="currentColor"/><circle cx="40" cy="28" r="10" fill="currentColor"/><path d="M32 22q6-7 14-1" stroke="#fff7" stroke-width="2" fill="none"/><circle cx="37" cy="26" r="1.5" fill="#fff"/><circle cx="44" cy="26" r="1.5" fill="#fff"/></svg>';
spiders.querySelectorAll('.dangling-spider').forEach(el=>{el.innerHTML=spiderArt});
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
function updateFlight(){flightFrame=0;const visible=cover.hidden&&scrollY>=65&&!reducedMotion.matches;flyer.hidden=!visible;realFlyer.hidden=!visible;spiders.hidden=!visible;flightWeb.toggleAttribute('hidden',!visible);if(!visible)return;
  const mobile=innerWidth<760,width=mobile?250:330,height=width*359/557,rope=Math.min(flightHeight*(mobile?.35:.42),mobile?290:430),anchorX=innerWidth*(mobile?.9:.88),phase=scrollY/Math.max(460,flightHeight*.8)*1.75,angle=.43*Math.sin(phase);
  const handX=Math.min(innerWidth-(mobile?28:80),anchorX+Math.sin(angle)*rope),handY=-24+Math.cos(angle)*rope;
  flyer.style.transform=`translate3d(${(handX-width*.72).toFixed(2)}px,${(handY-height*.54).toFixed(2)}px,0) rotate(${(-angle*24).toFixed(2)}deg)`;
  flightWeb.setAttribute('viewBox',`0 0 ${innerWidth} ${innerHeight}`);
  const thread=`M ${anchorX.toFixed(1)} -24 C ${(anchorX+Math.sin(angle)*11).toFixed(1)} ${(handY*.28).toFixed(1)}, ${(handX-Math.sin(angle)*13).toFixed(1)} ${(handY*.75).toFixed(1)}, ${handX.toFixed(1)} ${handY.toFixed(1)}`;
  webShadow.setAttribute('d',thread);webThread.setAttribute('d',thread);
  const realWidth=mobile?132:188,realHeight=realWidth*547/365,realAnchor=innerWidth*(mobile?.17:.23),realPhase=scrollY/Math.max(520,flightHeight*.9),realAngle=-.28*Math.sin(realPhase*1.27+.8),realRope=Math.min(flightHeight*.45,390);
  const realHandX=realAnchor+Math.sin(realAngle)*realRope,realHandY=-30+Math.cos(realAngle)*realRope+Math.sin(realPhase*.4)*15;
  realFlyer.style.transform=`translate3d(${(realHandX-realWidth*.48).toFixed(2)}px,${(realHandY-realHeight*.47).toFixed(2)}px,0) rotate(${(-realAngle*33).toFixed(2)}deg)`;
  const realPath=`M ${realAnchor.toFixed(1)} -30 Q ${(realAnchor+Math.sin(realAngle)*22).toFixed(1)} ${(realHandY*.48).toFixed(1)} ${realHandX.toFixed(1)} ${realHandY.toFixed(1)}`;
  realShadow.setAttribute('d',realPath);realThread.setAttribute('d',realPath);
  spiders.querySelectorAll('.dangling-spider').forEach((el,i)=>{const journey=(scrollY*(.17+i*.025)+(i*91))%Math.max(270,flightHeight*.62),drop=45+journey;el.style.setProperty('--drop',`${drop.toFixed(2)}px`);el.style.transform=`translate3d(0,${drop.toFixed(2)}px,0)`});
}
function queueFlight(){if(!flightFrame)flightFrame=requestAnimationFrame(updateFlight)}
addEventListener('scroll',queueFlight,{passive:true});addEventListener('resize',()=>{if(innerWidth!==flightWidth){flightWidth=innerWidth;flightHeight=Math.max(innerHeight,document.documentElement.clientHeight)}queueFlight()});reducedMotion.addEventListener('change',queueFlight);
const autoBtn=document.getElementById('autoScrollButton');let autoFrame=0,lastFrame=0,autoScrolling=false,autoTarget=0,autoSpeed=0;
function stopAuto(){autoScrolling=false;cancelAnimationFrame(autoFrame);autoFrame=0;lastFrame=0;autoSpeed=0;document.documentElement.classList.remove('auto-reading');autoBtn.textContent='▶ Scroll';autoBtn.setAttribute('aria-label','Lanjutkan scroll otomatis');autoBtn.setAttribute('aria-pressed','false')}
function autoTick(time){if(!autoScrolling)return;const page=document.scrollingElement;if(lastFrame){const dt=Math.min(32,Math.max(0,time-lastFrame));autoSpeed+=(78-autoSpeed)*Math.min(1,dt/500);autoTarget=Math.min(page.scrollHeight-innerHeight,autoTarget+autoSpeed*dt/1000);page.scrollTop=autoTarget;if(page.scrollTop+innerHeight>=page.scrollHeight-3){stopAuto();return}}lastFrame=time;autoFrame=requestAnimationFrame(autoTick)}
function startAuto(explicit=false){if(reducedMotion.matches&&!explicit)return;document.documentElement.classList.add('auto-reading');const page=document.scrollingElement;if(page.scrollTop+innerHeight>=page.scrollHeight-4)page.scrollTop=0;autoTarget=page.scrollTop;autoSpeed=0;autoScrolling=true;autoBtn.textContent='Ⅱ Scroll';autoBtn.setAttribute('aria-label','Jeda scroll otomatis');autoBtn.setAttribute('aria-pressed','true');autoFrame=requestAnimationFrame(autoTick)}
autoBtn.addEventListener('click',()=>autoScrolling?stopAuto():startAuto(true));
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',()=>{if(autoScrolling)stopAuto()}));
for(const type of ['wheel','touchmove','keydown'])addEventListener(type,event=>{if(type==='keydown'&&!['ArrowDown','ArrowUp','PageDown','PageUp','Home','End',' '].includes(event.key))return;if(autoScrolling)stopAuto()},{passive:true});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(autoScrolling)stopAuto();if(musicPlaying)stopMusic()}});
document.getElementById('open').addEventListener('click',()=>{main.inert=false;document.documentElement.classList.add('auto-reading');document.scrollingElement.scrollTop=0;cover.classList.add('closed');btn.hidden=false;autoBtn.hidden=false;if(reducedMotion.matches||window.__INVITATION_PREVIEW__)stopAuto();startMusic();setTimeout(()=>{cover.hidden=true;queueFlight();if(!window.__INVITATION_PREVIEW__&&!reducedMotion.matches)startAuto()},850)});
})();
