'use strict';
(async()=>{
const safeURL=(url,protocols=['https:'])=>{if(typeof url!=='string'||!url.trim())return '';try{const u=new URL(url,document.baseURI);return protocols.includes(u.protocol)?u.href:''}catch{return''}};
const themeAssets=new Set(['spider-swing.jpeg','spider-relax.jpeg','spider-hang.jpeg','spider-hero.jpeg']);
const isThemeAsset=src=>typeof src==='string'&&themeAssets.has(src.split(/[/?#]/).pop());
let data;try{const response=await fetch('config.json',{cache:'no-store'});if(!response.ok)throw Error('config');data=await response.json();try{const cloud=window.__INVITATION_PREVIEW__?null:await import('./firebase-store.js');const latest=cloud?await cloud.loadInvitation():null;if(latest?.hero&&latest?.event)data=latest}catch(e){console.warn('Menggunakan undangan cadangan:',e)}}catch{document.body.textContent='Undangan belum dapat dimuat. Coba segarkan halaman.';return}
const get=path=>path.split('.').reduce((o,k)=>o?.[k],data)??'';
const setText=(el,value)=>{el.textContent=String(value)};
document.querySelectorAll('[data-bind]').forEach(el=>setText(el,get(el.dataset.bind)));
for(const [key,visible] of Object.entries(data.sections||{})){const el=document.getElementById(key);if(el)el.hidden=!visible; if(key==='details')document.getElementById('event').hidden=!visible}
document.title=`Undangan Ulang Tahun ${data.hero.name}`;
const coverPhoto=isThemeAsset(data.hero.cover)?'':safeURL(data.hero.cover,['https:','data:']);if(coverPhoto){document.getElementById('customCoverImage').src=coverPhoto;document.getElementById('customCover').hidden=false}
for(const color of ['red','blue','gold','cream'])if(/^#[0-9a-fA-F]{6}$/.test(data.theme?.[color]||''))document.documentElement.style.setProperty('--'+color,data.theme[color]);
const params=new URLSearchParams(location.search),invitee=(params.get('to')||'Sahabat dan keluarga').slice(0,100);setText(document.getElementById('invitee'),invitee);
const portrait=isThemeAsset(data.hero.portrait)?'':safeURL(data.hero.portrait,['https:','data:']);if(portrait){const img=document.getElementById('heroPortrait');img.src=portrait;img.hidden=false;document.querySelector('.portrait-default').hidden=true}
const grid=document.getElementById('galleryGrid');const photos=(data.extras.gallery||[]).filter(item=>!isThemeAsset(item.src)&&safeURL(item.src,['https:','data:']));if(photos.length){photos.forEach(item=>{const wrap=document.createElement('div');wrap.className='gallery-item gallery-item-'+(grid.children.length+1);const img=document.createElement('img');img.src=safeURL(item.src,['https:','data:']);img.alt=item.caption||'Foto anak';img.loading='lazy';const caption=document.createElement('p');setText(caption,item.caption||'Momen spesial');wrap.append(img,caption);grid.append(wrap)})}else{const empty=document.createElement('div');empty.className='gallery-empty';empty.textContent='Foto-foto spesial anak akan tampil di sini setelah diunggah lewat admin ✦';grid.append(empty)}
const start=new Date(`${data.event.date}T${data.event.start||'00:00'}:00+08:00`),end=new Date(`${data.event.date}T${data.event.end||'23:59'}:00+08:00`);const valid=Boolean(data.event.date)&&!Number.isNaN(start.getTime());document.getElementById('eventDate').textContent=valid?new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Makassar'}).format(start):'Tanggal menyusul';document.getElementById('eventTime').textContent= data.event.start?`${data.event.start} – ${data.event.end||'selesai'} WITA`:'Waktu menyusul';
const calendar=document.getElementById('calendarLink');if(valid){const utc=date=>date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');calendar.href=`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent('Ulang Tahun '+data.hero.name)}&dates=${utc(start)}/${utc(end>start?end:new Date(start.getTime()+7200000))}&details=${encodeURIComponent(data.invitation.message)}&location=${encodeURIComponent(data.event.venue+', '+data.event.address)}`}else calendar.hidden=true;
const map=document.getElementById('mapLink');map.href=safeURL(data.event.map)||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(data.event.venue+' '+data.event.address)}`;
const phone=String(data.extras.whatsapp||'').replace(/\D/g,'');const rsvp=document.getElementById('rsvpLink');if(phone){rsvp.href=`https://wa.me/${phone}?text=${encodeURIComponent((data.extras.rsvpMessage||'Halo, saya akan hadir di ulang tahun {name}.').replaceAll('{name}',data.hero.name)+' Dari: '+invitee)}`}else{rsvp.hidden=true;document.getElementById('rsvpHint').textContent='Kontak konfirmasi akan segera tersedia.'}
function tick(){const diff=valid?Math.max(0,start.getTime()-Date.now()):0;const vals=[Math.floor(diff/86400000),Math.floor(diff/3600000)%24,Math.floor(diff/60000)%60,Math.floor(diff/1000)%60];['days','hours','minutes','seconds'].forEach((id,i)=>document.getElementById(id).textContent=String(vals[i]).padStart(2,'0'));if(valid&&diff===0)document.getElementById('countdownNote').textContent='Hari istimewa telah tiba!'}tick();setInterval(tick,1000);
const audio=document.getElementById('music'),btn=document.getElementById('musicButton'),music=safeURL(data.extras.music,['https:']);if(music){audio.src=music;btn.hidden=false;btn.addEventListener('click',async()=>{if(audio.paused){try{await audio.play();btn.classList.add('playing');btn.setAttribute('aria-label','Jeda musik')}catch{btn.title='Musik tidak dapat diputar. Gunakan tautan langsung berkas audio.'}}else{audio.pause();btn.classList.remove('playing');btn.setAttribute('aria-label','Putar musik')}})}
const cover=document.getElementById('cover'),main=document.getElementById('main');
const flyer=document.getElementById('scrollSpider'),flightWeb=document.getElementById('flightWeb'),webShadow=document.getElementById('flightWebShadow'),webThread=document.getElementById('flightWebThread');let flightFrame=0;
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
function updateFlight(){flightFrame=0;const visible=cover.hidden&&scrollY>=65&&!reducedMotion.matches;flyer.hidden=!visible;flightWeb.toggleAttribute('hidden',!visible);if(!visible)return;
  const mobile=innerWidth<760,width=mobile?250:330,height=width*359/557,rope=Math.min(innerHeight*(mobile?.35:.42),mobile?290:430),anchorX=innerWidth*(mobile?.9:.88),phase=scrollY/Math.max(460,innerHeight*.8)*1.75,angle=.43*Math.sin(phase);
  const handX=anchorX+Math.sin(angle)*rope,handY=-24+Math.cos(angle)*rope;
  flyer.style.left=Math.round(handX-width*.72)+'px';flyer.style.top=Math.round(handY-height*.54)+'px';flyer.style.setProperty('--swing-tilt',Math.round(-angle*24)+'deg');
  flightWeb.setAttribute('viewBox',`0 0 ${innerWidth} ${innerHeight}`);
  const thread=`M ${anchorX.toFixed(1)} -24 C ${(anchorX+Math.sin(angle)*11).toFixed(1)} ${(handY*.28).toFixed(1)}, ${(handX-Math.sin(angle)*13).toFixed(1)} ${(handY*.75).toFixed(1)}, ${handX.toFixed(1)} ${handY.toFixed(1)}`;
  webShadow.setAttribute('d',thread);webThread.setAttribute('d',thread);
}
function queueFlight(){if(!flightFrame)flightFrame=requestAnimationFrame(updateFlight)}
addEventListener('scroll',queueFlight,{passive:true});addEventListener('resize',queueFlight);reducedMotion.addEventListener('change',queueFlight);
document.getElementById('open').addEventListener('click',async()=>{main.inert=false;cover.classList.add('closed');setTimeout(()=>{cover.hidden=true;queueFlight()},700);if(music){try{await audio.play();btn.classList.add('playing');btn.setAttribute('aria-label','Jeda musik')}catch{/* manual control remains visible */}}});
})();
